### ISSUE TITLE
sha1 which is provided on Chef's site doesn't suit to this cookbook.

### ISSUE THREAD

**Issue by fog1985** [opscode-cookbooks/push-jobs#15]
On chef's site we can find SHA1 key: 
site: https://downloads.chef.io/push-jobs-client/windows/
Key value: 38b43b5895e44c4c64c5ae19337f7bc918ffdd2b

It works for installing push jobs on client which has chef-client with less than 12 version. 

But on nodes which have chef-client of version 12 it fails as follow:
 - does not match checksum on content (411520)

So instead of provided by Chef "38b43b5..." it determines this file as having checksum "411520...".

I have tried to download that file and checked checksum with md5 and got what is provided by Chef:
c:\checksum>fciv.exe c:\opscode-push-jobs-client-windows-1.1.5-1.windows.msi -sh
a1
//
// File Checksum Integrity Verifier version 2.05.
//
38b43b5895e44c4c64c5ae19337f7bc918ffdd2b c:\opscode-push-jobs-client-windows-1.1
.5-1.windows.msi

So checksum on the site is correct.
But it seems that something is wrong with decryption during download process during default recipe run from push-jobs cookbook.

Can you please check it?
Thank you in advance. 

Regards,
Taras.

**Comment by jtimberman** [comment]
I would compare the SHA1 of the MSI you downloaded, and then calculate the SHA256 if the SHA1's match.
