### ISSUE TITLE
RHEL 7 Support

### ISSUE THREAD

**Issue by dolendupes** [opscode-cookbooks/push-jobs#22]
The chef-client run for the current cookbook does not successfully complete and ends up in an infinite loop at the following:

    [2015-02-27T17:20:47+00:00] DEBUG: waiting until named pipe /etc/service/opscode-push-jobs-client/supervise/ok exists.
    [2015-02-27T17:20:48+00:00] DEBUG: .
    [2015-02-27T17:20:49+00:00] DEBUG: .
    [2015-02-27T17:20:50+00:00] DEBUG: .

If I stop the chef-client run and execute the following '/opt/opscode-push-jobs-client/bin/pushy-client -c /etc/chef/push-jobs-client.rb", then everything seems to work.  I believe there is an issue with runit.

**Comment by nexeck** [comment]
+1 Please add RHEL 7 support

**Comment by tzniuta** [comment]
hm.. no news yet??

**Comment by irvingpop** [comment]
RHEL7 works now -  but you need to use a newer version of the runit cookbook (I tested with 1.7.2) and a newer Chef client that understands the systemd service provider (any 12.x client should be OK, I verified with 12.4.0)

To ensure RHEL7 continues to work I created PR #35
