### ISSUE TITLE
push jobs fail with ArgumentError: invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by runwaldarshu** [opscode-cookbooks/push-jobs#25]
Currently due to no encoding set on the chef config if there are cookbooks involved with data non ASCII format the push job fails.
It will be nice to allow support for push-jobs cookbook to allow ENV variable setting so that we can set LC_ALL as per https://tickets.opscode.com/browse/CHEF-3304 

There are copule of ways we can do it and based on which way we would like to resolve it I will submit PR
- We can allow configuration with key and value pairs for any environment variables and then set in the push-jobs-client.rb.erb template
- We can allow configuration for cookbook name for push-jobs-client.rb.erb template so that any consumer can write their own configuration in the wrapper cookbook and use that config for deploy

Any other options are welcome as well.

**Comment by manderson26** [comment]
Merged your fix. Thanks!
