### ISSUE TITLE
Documentation - Usage - configuration file

### ISSUE THREAD

**Issue by GoodMirek** [opscode-cookbooks/push-jobs#33]
It is not clear from README.MD in which configuration file is the whitelist stored.

**Comment by jtimberman** [comment]
> This recipe ensures the platform-specific configuration directory (/etc/chef) is created, and renders the configuration file (push-jobs-client.rb) using the whitelist attribute.

**Comment by GoodMirek** [comment]
Please would you be so nice and give other beginners a chance to find it out from the README.md ?

**Comment by jtimberman** [comment]
That is in the README.md.

**Comment by GoodMirek** [comment]
It was quite difficult for me as a beginner to decode this forward declaration. I believe it might be improved in a way allowing easier understanding.

**Comment by andrewelizondo** [comment]
This looks fine to me as well, @goodmirek what would you change in the documentation to make it easier to understand?
