### ISSUE TITLE
Change in client_key path in v2.4.0

### ISSUE THREAD

**Issue by gshively11** [opscode-cookbooks/push-jobs#38]
In the latest release, [this line](https://github.com/opscode-cookbooks/push-jobs/blob/master/templates/default/push-jobs-client.rb.erb#L15) was added, which now forces the push jobs client to look for the client key in /etc/chef/secure.  However, my client key has always been stored in /etc/chef, and previous versions of the push job client have worked.  This prevents the push jobs service from starting.  

I wouldn't expect a breaking change like this in a 2.x.0 bump, but maybe my stuff is not configured according to standards.  Can you add some clarification to this change please?

**Comment by someara** [comment]
I'm pretty sure this is a regressions... @manderson26 thoughts?
-s

**Comment by alexpop** [comment]
I also bumped into this on a CentOS 6.6 node using push-jobs cookbook v2.4.0

**Comment by alexpop** [comment]
Fixed in cookbook version 2.4.1
